name: Fadah
description: Fadah (Finally a Decent Auction House) is the fast, modern and advanced auction house plugin that you have been looking for!
authors: [Preva1l]
website: https://discord.gg/4KcF7S94HF
version: '${version}'

softdepend: [PlaceholderAPI, EcoItems, zAuctionHouseV3, AuctionHouse, RedisEconomy, CoinsEngine, Vault]

load: POSTWORLD

folia-supported: true

main: info.preva1l.fadah.Fadah
api-version: '1.16'
libraries:
  - redis.clients:jedis:${jedis_version}
  - org.apache.commons:commons-pool2:${acp2_version}
  - org.mongodb:mongodb-driver-sync:${mongo_version}
  - org.xerial:sqlite-jdbc:${sqlite_version}
  - com.mysql:mysql-connector-j:${mysql_version}
  - org.mariadb.jdbc:mariadb-java-client:${mariadb_version}
  - net.kyori:adventure-text-minimessage:${minimessage_version}
  - net.kyori:adventure-api:${minimessage_version}
  - net.kyori:adventure-platform-bukkit:${mm_platform_version}
  - com.influxdb:influxdb-client-java:${influxdb_version}
  - com.zaxxer:HikariCP:${hikari_version}
  - org.mozilla:rhino:${rhino_version}
  - de.exlll:configlib-yaml:${configlib_version}

permissions:
  fadah.max-listings.<amount>:
    description: The amount of items a player can list at any one time.
  fadah.listing-tax.<amount>:
    description: The percentage a player will get taxed when creating a listing.
  fadah.advert-price.<amount>:
    description: The cost of a listing advertisement.
  fadah.use:
    default: true
  fadah.collection-box:
    default: true
  fadah.expired-items:
    default: true
  fadah.help:
    default: true
  fadah.profile:
    default: true
  fadah.active-listings:
    default: true
  fadah.watch:
    default: true
  fadah.manage.*:
    children:
      - fadah.manage.profile
      - fadah.manage.active-listings
      - fadah.manage.expired-items
      - fadah.manage.collection-box